import { AiEvent } from './events'
import { appendWslenv } from './runtimeTargets'

export const PI_HOOK_ENDPOINT_ENV = 'VIBBY_PI_HOOK_ENDPOINT'
export const PI_HOOK_DROP_DIR_ENV = 'VIBBY_PI_HOOK_DROP_DIR'
export const PI_HOOK_SESSION_ENV = 'VIBBY_PI_HOOK_SESSION_ID'
export const PI_HOOK_LOG_ENV = 'VIBBY_PI_LOG_PATH'
export const PI_EXTENSION_FILE_NAME = 'vibby-extension.ts'
export const PI_HOOK_ROUTE_FILE_NAME = 'vibby-route.json'

const PI_TEMP_DIR_PREFIX = 'vibby-pi-'

export interface PiHookRecovery {
    sessionId: string
    dropDir: string
    tempName: string
}

/**
 * Returns the distro encoded in a direct `wsl.exe` Pi launch.
 *
 * Restored tabs created by older builds may not carry aiCli.targetId, but the
 * wrapper arguments remain authoritative. Without this fallback a WSL launch
 * receives a Windows `C:\...` extension path and Pi resolves it below $HOME.
 */
export function piWslDistroFromArgs (args: string[]): string|null {
    if (
        args.length >= 6 &&
        args[0] === '--distribution' &&
        args[4] === '--exec'
    ) {
        return args[1]?.trim() || null
    }
    return null
}

function isStalePiExtensionPath (value: string|undefined): boolean {
    const normalized = (value ?? '').replace(/\\/g, '/')
    const parent = normalized.slice(0, Math.max(0, normalized.lastIndexOf('/')))
    return normalized.toLowerCase().endsWith(`/${PI_EXTENSION_FILE_NAME}`) &&
        parent.split('/').some(part => part.startsWith(PI_TEMP_DIR_PREFIX))
}

/** Removes only extensions generated by Vibby, preserving every user-supplied `-e`. */
export function withoutStalePiHookArgs (args: string[]): string[] {
    const clean: string[] = []
    for (let i = 0; i < args.length; i++) {
        if (
            (args[i] === '-e' || args[i] === '--extension') &&
            isStalePiExtensionPath(args[i + 1])
        ) {
            i++
        } else if (
            args[i].startsWith('--extension=') &&
            isStalePiExtensionPath(args[i].slice('--extension='.length))
        ) {
            continue
        } else {
            clean.push(args[i])
        }
    }
    return clean
}

/**
 * Route metadata retained only while a recoverable PTY is alive. The temp
 * directory name must agree in both the extension argument and environment,
 * so the file-drop consumer never follows an arbitrary persisted path.
 */
export function piHookRecovery (
    args: string[],
    env: Record<string, string>,
): PiHookRecovery|null {
    const rawSessionId: unknown = env[PI_HOOK_SESSION_ENV]
    const rawDropDir: unknown = env[PI_HOOK_DROP_DIR_ENV]
    const sessionId = typeof rawSessionId === 'string' ? rawSessionId.trim() : ''
    const dropDir = typeof rawDropDir === 'string' ? rawDropDir.trim() : ''
    if (!sessionId || !/^[\w-]{1,64}$/.test(sessionId) || !dropDir) {
        return null
    }

    let extensionPath: string|null = null
    for (let i = 0; i < args.length; i++) {
        if ((args[i] === '-e' || args[i] === '--extension') && isStalePiExtensionPath(args[i + 1])) {
            extensionPath = args[i + 1]
            break
        }
        if (args[i].startsWith('--extension=')) {
            const value = args[i].slice('--extension='.length)
            if (isStalePiExtensionPath(value)) {
                extensionPath = value
                break
            }
        }
    }
    if (!extensionPath) {
        return null
    }

    const normalizedExtension = extensionPath.replace(/\\/g, '/')
    const tempName = normalizedExtension.split('/').slice(-2, -1)[0] ?? ''
    const normalizedDrop = dropDir.replace(/[\\/]+$/, '').replace(/\\/g, '/')
    if (
        !tempName.startsWith(PI_TEMP_DIR_PREFIX) ||
        normalizedDrop.split('/').pop() !== tempName
    ) {
        return null
    }
    return { sessionId, dropDir, tempName }
}

/**
 * Inserts Pi's extension argument after any platform launcher.
 *
 * Windows npm packages may resolve to cmd or PowerShell shims; WSL profiles
 * wrap the Linux executable with wsl.exe. macOS/Linux take the direct branch.
 */
export function injectPiExtensionArgs (wrappedArgs: string[], extensionPath: string): string[] {
    if (wrappedArgs.length >= 6 && wrappedArgs[0] === '--distribution' && wrappedArgs[4] === '--exec') {
        return [...wrappedArgs.slice(0, 6), '-e', extensionPath, ...wrappedArgs.slice(6)]
    }
    if (wrappedArgs.length >= 2 && wrappedArgs[0].toLowerCase() === '/c') {
        return [wrappedArgs[0], wrappedArgs[1], '-e', extensionPath, ...wrappedArgs.slice(2)]
    }
    const fileIndex = wrappedArgs.findIndex(arg => arg.toLowerCase() === '-file')
    if (fileIndex >= 0 && fileIndex + 1 < wrappedArgs.length) {
        const commandEnd = fileIndex + 2
        return [...wrappedArgs.slice(0, commandEnd), '-e', extensionPath, ...wrappedArgs.slice(commandEnd)]
    }
    return ['-e', extensionPath, ...wrappedArgs]
}

function text (value: unknown): string {
    return typeof value === 'string' ? value : ''
}

function record (value: unknown): Record<string, unknown> {
    return typeof value === 'object' && value !== null && !Array.isArray(value)
        ? value as Record<string, unknown>
        : {}
}

function basename (value: unknown): string {
    const path = text(value)
    const index = Math.max(path.lastIndexOf('/'), path.lastIndexOf('\\'))
    return index >= 0 ? path.slice(index + 1) : path
}

/** Never expose command arguments: prompts and credentials often live there. */
function commandName (value: unknown): string {
    const command = text(value).trim()
    const first = /^(?:"([^"]+)"|'([^']+)'|(\S+))/.exec(command)?.slice(1).find(Boolean) ?? ''
    return basename(first).replace(/\.(exe|cmd|bat|ps1)$/i, '') || 'command'
}

function toolSummary (toolName: string, input: Record<string, unknown>): string {
    switch (toolName.toLowerCase()) {
        case 'bash':
            return `command: ${text(input['commandName']) || commandName(input['command'])}`
        case 'read':
            return `read: ${basename(input['fileName'] ?? input['file_path'] ?? input['path']) || 'files'}`
        case 'apply_patch':
        case 'edit':
        case 'write':
            return `edit: ${basename(input['fileName'] ?? input['file_path'] ?? input['path']) || 'files'}`
        case 'agent':
        case 'spawn_agent':
            return 'agent'
        default:
            return `tool: ${toolName || 'working'}`
    }
}

/**
 * Environment variables passed to a Pi session so its generated extension knows
 * where to send events. Native sessions post to the loopback HTTP endpoint;
 * WSL sessions write to a drop directory because NAT-mode distros cannot reach
 * the Windows host loopback reliably.
 */
export function piHookEnvironment (
    endpoint: string,
    dropDir?: string | null,
    sessionId?: string,
    existingEnv: Record<string, string> = {},
    logPath?: string,
): Record<string, string> {
    const env: Record<string, string> = {
        ...existingEnv,
        [PI_HOOK_ENDPOINT_ENV]: endpoint,
    }
    if (logPath) {
        env[PI_HOOK_LOG_ENV] = logPath
    }
    if (dropDir && sessionId) {
        env[PI_HOOK_DROP_DIR_ENV] = dropDir
        env[PI_HOOK_SESSION_ENV] = sessionId
        env.WSLENV = appendWslenv(existingEnv.WSLENV, [
            PI_HOOK_DROP_DIR_ENV,
            PI_HOOK_SESSION_ENV,
            ...logPath ? [PI_HOOK_LOG_ENV] : [],
        ])
    }
    return env
}

/**
 * Generates a self-contained Pi extension that forwards lifecycle hooks to vibby.
 *
 * The source uses only Node.js built-ins so it has no external dependencies when
 * loaded by `pi -e <path>`. The endpoint is not baked in; it is read from the
 * environment so the same cached/generated source can be reused across sessions
 * if desired.
 */
export function buildPiExtensionSource (): string {
    return `import * as fs from "fs"
import * as path from "path"
import * as http from "http"

const DEFAULT_ENDPOINT = process.env.${PI_HOOK_ENDPOINT_ENV}
const DEFAULT_DROP_DIR = process.env.${PI_HOOK_DROP_DIR_ENV}
const DEFAULT_SESSION_ID = process.env.${PI_HOOK_SESSION_ENV}
const LOG_PATH = process.env.${PI_HOOK_LOG_ENV}
const ROUTE_PATH = LOG_PATH ? path.join(path.dirname(LOG_PATH), "${PI_HOOK_ROUTE_FILE_NAME}") : null
const MAX_TEXT_LENGTH = 512
const MAX_EVENT_BYTES = 64 * 1024

let loggedDrop = false
let loggedHttp = false
let thinkingActive = false
let runErrored = false

function logError(message) {
    if (!LOG_PATH) return
    try {
        fs.appendFileSync(LOG_PATH, new Date().toISOString() + " " + message + "\\n")
    } catch {}
}

function stringValue(value) {
    return typeof value === "string" ? value : ""
}

function limitedText(value) {
    return stringValue(value).slice(0, MAX_TEXT_LENGTH)
}

function baseName(value) {
    const input = stringValue(value)
    const index = Math.max(input.lastIndexOf("/"), input.lastIndexOf("\\\\"))
    return index >= 0 ? input.slice(index + 1) : input
}

function commandName(value) {
    const command = stringValue(value).trim()
    const first = /^(?:"([^"]+)"|'([^']+)'|(\\S+))/.exec(command)?.slice(1).find(Boolean) || ""
    return baseName(first).replace(/\\.(exe|cmd|bat|ps1)$/i, "") || "command"
}

function compactToolEvent(event) {
    const toolName = stringValue(event?.toolName)
    const input = event?.input && typeof event.input === "object" ? event.input : {}
    const compact = { toolName }
    switch (toolName.toLowerCase()) {
        case "bash":
            compact.commandName = commandName(input.command)
            break
        case "read":
        case "edit":
        case "write":
        case "apply_patch":
            compact.fileName = baseName(input.path || input.file_path)
            break
    }
    if (typeof event?.isError === "boolean") {
        compact.isError = event.isError
    }
    return compact
}

function currentRoute() {
    let route = {
        endpoint: DEFAULT_ENDPOINT,
        dropDir: DEFAULT_DROP_DIR,
        sessionId: DEFAULT_SESSION_ID,
    }
    if (!ROUTE_PATH) return route
    try {
        const saved = JSON.parse(fs.readFileSync(ROUTE_PATH, "utf8"))
        route = {
            endpoint: typeof saved?.endpoint === "string" ? saved.endpoint : route.endpoint,
            dropDir: typeof saved?.dropDir === "string" ? saved.dropDir : route.dropDir,
            sessionId: typeof saved?.sessionId === "string" ? saved.sessionId : route.sessionId,
        }
    } catch {}
    return route
}

function sendEvent(piEvent) {
    const route = currentRoute()
    if (!route.endpoint && !route.dropDir) return
    const payload = { ...piEvent }
    if (route.sessionId) {
        payload.vibby_session_id = route.sessionId
    }
    let body
    try {
        body = JSON.stringify(payload)
        if (Buffer.byteLength(body, "utf8") > MAX_EVENT_BYTES) {
            logError("event discarded: payload too large")
            return
        }
    } catch (err) {
        logError("serialize failed: " + err.message)
        return
    }

    if (route.dropDir && route.sessionId) {
        // The Windows file-drop poller accepts the same six-character nonce
        // contract used by mktemp-based Claude and Codex hooks.
        const nonce = Math.random().toString(36).slice(2, 8).padEnd(6, "0")
        const tmp = path.join(route.dropDir, route.sessionId + "." + nonce)
        try {
            fs.writeFileSync(tmp, body)
            fs.renameSync(tmp, tmp + ".json")
        } catch (err) {
            if (!loggedDrop) {
                loggedDrop = true
                logError("drop failed: " + err.message)
            }
        }
        return
    }

    if (route.endpoint) {
        try {
            const url = new URL(route.endpoint)
            const req = http.request({
                hostname: url.hostname,
                port: url.port,
                path: url.pathname + url.search,
                method: "POST",
                headers: { "Content-Type": "application/json" },
            }, response => response.resume())
            req.setTimeout(3000, () => req.destroy(new Error("timeout")))
            req.on("error", (err) => {
                if (!loggedHttp) {
                    loggedHttp = true
                    logError("post failed: " + err.message)
                }
            })
            req.end(body)
        } catch (err) {
            if (!loggedHttp) {
                loggedHttp = true
                logError("post failed: " + err.message)
            }
        }
    }
}

export default function (pi) {
    pi.on("session_start", () => sendEvent({ type: "session_start" }))
    pi.on("input", (event) => {
        sendEvent({
            type: "input",
            event: {
                text: limitedText(event?.text),
                source: limitedText(event?.source),
            },
        })
        // input is a mutation hook: returning undefined can block Pi's composer.
        return { action: "continue" }
    })
    pi.on("agent_start", () => {
        runErrored = false
        sendEvent({ type: "responding" })
    })
    pi.on("message_update", (event) => {
        const updateType = event?.assistantMessageEvent?.type
        if (
            (updateType === "thinking_start" || updateType === "thinking_delta") &&
            !thinkingActive
        ) {
            thinkingActive = true
            // Forward only a marker: reasoning text is private and deltas are high-volume.
            sendEvent({ type: "thinking" })
        } else if (
            updateType === "thinking_end" ||
            updateType === "text_start" ||
            updateType === "done" ||
            updateType === "error"
        ) {
            if (thinkingActive && updateType !== "error") {
                sendEvent({ type: "responding" })
            }
            thinkingActive = false
            if (updateType === "error") {
                runErrored = true
                sendEvent({ type: "retrying" })
            }
        }
    })
    pi.on("tool_call", (event) => sendEvent({ type: "tool_call", event: compactToolEvent(event) }))
    pi.on("tool_result", (event) => sendEvent({ type: "tool_result", event: compactToolEvent(event) }))
    pi.on("turn_end", () => {
        thinkingActive = false
    })
    pi.on("agent_settled", () => sendEvent({
        type: runErrored ? "agent_error" : "agent_settled",
    }))
    pi.on("session_shutdown", () => sendEvent({ type: "session_shutdown" }))
}
`
}

/**
 * Converts Pi extension hook payloads to the vibby event protocol.
 *
 * Privacy rules mirror claudeHooks/codexHooks: prompts reach the summary, but
 * tool inputs, raw results, and file contents do not.
 */
export function translatePiHook (
    sessionId: string,
    payload: unknown,
    ts: number,
): AiEvent | null {
    const value = record(payload)
    const piType = text(value['type'])
    const event = record(value['event'])
    const base = { sessionId, ts, confidence: 'high' as const }

    switch (piType) {
        case 'session_start':
            return { ...base, kind: 'session-started', summary: 'ready' }
        case 'input': {
            if (text(event['source']) === 'extension') {
                return null
            }
            return { ...base, kind: 'prompt-submitted', summary: `user: ${text(event['text'])}` }
        }
        case 'thinking':
            return { ...base, kind: 'thinking', summary: 'thinking' }
        case 'responding':
            return { ...base, kind: 'responding', summary: 'responding' }
        case 'retrying':
            return { ...base, kind: 'retrying', summary: 'retrying' }
        case 'agent_error':
            return { ...base, kind: 'session-error', summary: 'Pi request failed' }
        case 'tool_call': {
            const toolName = text(event['toolName'])
            return { ...base, kind: 'tool-call', summary: toolSummary(toolName, event) }
        }
        case 'tool_result': {
            const toolName = text(event['toolName'])
            return { ...base, kind: 'tool-result', summary: `tool: ${toolName || 'working'}` }
        }
        case 'agent_settled':
            return { ...base, kind: 'turn-completed', summary: 'done' }
        case 'turn_end':
        case 'agent_end':
            return null
        case 'session_shutdown':
            return { ...base, kind: 'session-ended', summary: 'ended' }
        default:
            return null
    }
}
