import { AiCliRegistryEntry } from './api'

const VERSION = /(\d+\.\d+\.\d+\S*)/

export const AI_CLI_REGISTRY: AiCliRegistryEntry[] = [
    {
        id: 'claude-code',
        name: 'Claude Code',
        binaries: ['claude'],
        runtimeMarkers: ['@anthropic-ai/claude-code'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/claude-code.svg'),
        tier: 'full',
        docsUrl: 'https://code.claude.com/docs',
    },
    {
        id: 'codex',
        name: 'Codex CLI',
        binaries: ['codex'],
        runtimeMarkers: ['@openai/codex'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/codex.svg'),
        tier: 'full',
        docsUrl: 'https://github.com/openai/codex',
    },
    {
        id: 'gemini-cli',
        name: 'Gemini CLI',
        binaries: ['gemini'],
        runtimeMarkers: ['@google/gemini-cli'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/gemini-cli.svg'),
        tier: 'launch',
        docsUrl: 'https://github.com/google-gemini/gemini-cli',
    },
    {
        id: 'opencode',
        name: 'OpenCode',
        binaries: ['opencode'],
        runtimeMarkers: ['opencode-ai/', 'opencode/bin'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/opencode.svg'),
        tier: 'full',
        docsUrl: 'https://opencode.ai',
    },
    {
        // two letters, and a word that turns up in ordinary arguments — this
        // one leans on the marker and on being the process itself, never on a
        // bare token (see cliMatch.looksInvoked)
        id: 'pi',
        name: 'pi',
        binaries: ['pi'],
        runtimeMarkers: ['@earendil-works/pi-coding-agent'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/pi.svg'),
        tier: 'launch',
    },
    {
        id: 'github-copilot',
        name: 'GitHub Copilot CLI',
        binaries: ['copilot'],
        runtimeMarkers: ['@github/copilot', 'github/copilot-cli'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/github-copilot.svg'),
        tier: 'launch',
        docsUrl: 'https://docs.github.com/en/copilot/how-tos/use-copilot-agents/use-copilot-cli',
    },
    {
        id: 'antigravity-cli',
        name: 'Antigravity CLI',
        binaries: ['agy'],
        runtimeMarkers: ['antigravity-cli'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/antigravity.svg'),
        tier: 'launch',
        docsUrl: 'https://antigravity.google/docs/cli-overview',
    },
    {
        id: 'cursor-agent',
        name: 'Cursor Agent CLI',
        binaries: ['cursor-agent'],
        runtimeMarkers: ['cursor-agent'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/cursor-agent.svg'),
        tier: 'launch',
        docsUrl: 'https://docs.cursor.com/en/cli/overview',
    },
    {
        id: 'cline',
        name: 'Cline CLI',
        binaries: ['cline'],
        runtimeMarkers: ['/node_modules/cline/', '@cline/cli'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/cline.svg'),
        tier: 'launch',
        docsUrl: 'https://docs.cline.bot/usage/cli-overview',
    },
    {
        id: 'qwen-code',
        name: 'Qwen Code',
        binaries: ['qwen'],
        runtimeMarkers: ['@qwen-code/qwen-code'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/qwen-code.svg'),
        tier: 'launch',
        docsUrl: 'https://github.com/QwenLM/qwen-code',
    },
    {
        id: 'goose',
        name: 'Goose',
        binaries: ['goose'],
        runtimeMarkers: ['aaif-goose/goose', 'block/goose'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/goose.svg'),
        tier: 'launch',
        docsUrl: 'https://github.com/aaif-goose/goose',
    },
    {
        id: 'kimi-code',
        name: 'Kimi Code',
        binaries: ['kimi'],
        runtimeMarkers: ['@moonshot-ai/kimi-code', 'moonshotai/kimi-code'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/kimi-code.svg'),
        tier: 'launch',
        docsUrl: 'https://moonshotai.github.io/kimi-code/',
    },
    {
        id: 'grok-build',
        name: 'Grok Build',
        binaries: ['grok'],
        runtimeMarkers: ['@xai-official/grok', 'xai-org/grok-build'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/grok-build.svg'),
        tier: 'launch',
        docsUrl: 'https://docs.x.ai/build/overview',
    },
    {
        id: 'kiro-cli',
        name: 'Kiro CLI',
        binaries: ['kiro-cli'],
        runtimeMarkers: ['kiro-cli'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/kiro-cli.svg'),
        tier: 'launch',
        docsUrl: 'https://kiro.dev/docs/cli/',
    },
    {
        id: 'kilo-code',
        name: 'Kilo Code CLI',
        binaries: ['kilo'],
        runtimeMarkers: ['@kilocode/cli'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/kilo-code.svg'),
        tier: 'launch',
        docsUrl: 'https://kilo.ai/docs/code-with-ai/platforms/cli',
    },
    {
        id: 'crush',
        name: 'Crush',
        binaries: ['crush'],
        runtimeMarkers: ['@charmland/crush', 'charmbracelet/crush'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/crush.svg'),
        tier: 'launch',
        docsUrl: 'https://github.com/charmbracelet/crush',
    },
    {
        id: 'openhands',
        name: 'OpenHands CLI',
        binaries: ['openhands'],
        runtimeMarkers: ['openhands-ai', 'openhands_cli'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/openhands.svg'),
        tier: 'launch',
        docsUrl: 'https://docs.openhands.dev/openhands/usage/cli/quick-start',
    },
    {
        id: 'factory-droid',
        name: 'Factory Droid',
        binaries: ['droid'],
        runtimeMarkers: ['/node_modules/droid/', '@factory-ai/droid'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/factory-droid.svg'),
        tier: 'launch',
        docsUrl: 'https://docs.factory.ai/cli/getting-started/overview',
    },
    {
        id: 'devin-cli',
        name: 'Devin CLI',
        binaries: ['devin'],
        runtimeMarkers: ['devin-cli'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/devin-cli.svg'),
        tier: 'launch',
        docsUrl: 'https://cli.devin.ai/reference/commands',
    },
    {
        id: 'continue-cli',
        name: 'Continue CLI',
        binaries: ['cn'],
        runtimeMarkers: ['@continuedev/cli', 'continuedev/continue'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/continue-cli.svg'),
        tier: 'launch',
        docsUrl: 'https://docs.continue.dev/cli/quickstart',
    },
    {
        id: 'amp',
        name: 'Amp',
        binaries: ['amp'],
        runtimeMarkers: ['@ampcode/cli', 'ampcode'],
        versionArgs: ['--version'],
        versionPattern: VERSION,
        icon: require('./icons/amp.svg'),
        tier: 'launch',
        docsUrl: 'https://ampcode.com/manual',
    },
]
